-- 021_generated_files_table.sql
-- Stores metadata for files generated by the code-executor agent (Code Interpreter).
-- Files themselves are stored in Cloudflare R2 under generated/{conversation_id}/{filename}.
-- This table lets the frontend re-render download cards when users return to a session.

CREATE TABLE IF NOT EXISTS generated_files (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id         uuid NOT NULL,
    filename        text NOT NULL,
    r2_url          text NOT NULL,
    size_bytes      bigint,
    mime_type       text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Index for fast per-conversation file lookups
CREATE INDEX IF NOT EXISTS idx_generated_files_conversation
    ON generated_files(conversation_id, created_at DESC);

-- Row Level Security: users can only read their own generated files
ALTER TABLE generated_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own generated files"
    ON generated_files FOR SELECT
    USING (user_id = auth.uid());

-- Backend service role bypasses RLS for INSERT/DELETE (no user-facing write policy needed)

-- Verify
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'generated_files'
ORDER BY ordinal_position;
