# capability_registry.py
# The "self-awareness" layer for Agent Ochuko.
# This is how the agent knows what it can do at runtime.
# Inject SYSTEM_PROMPT into every Foundry API call.

from datetime import datetime, timezone

# ─── 1. CAPABILITY REGISTRY ──────────────────────────────────────────────────
# Single source of truth. Add/remove capabilities here.
# The system prompt is built from this dict — not hardcoded.

CAPABILITY_REGISTRY = {
    "rendering": {
        "mermaid": {
            "description": "Flowcharts, sequence diagrams, ER diagrams, Gantt charts",
            "syntax": "```mermaid\n[diagram code]\n```",
            "when": "Architecture, workflows, data relationships, timelines",
        },
        "svg": {
            "description": "Scalable vector graphics — icons, illustrations, custom visuals",
            "syntax": "Output raw <svg>...</svg> markup inline",
            "when": "Custom diagrams, icons, geometric visuals, logos",
        },
        "images": {
            "description": "PNG/JPG files generated by Code Executor",
            "syntax": "Files from Code Executor are automatically displayed",
            "when": "Charts, plots, processed images, screenshots",
        },
        "markdown": {
            "description": "Full markdown including tables, bold, code blocks, lists",
            "syntax": "Standard markdown",
            "when": "All prose responses — always use markdown formatting",
        },
        "code_blocks": {
            "description": "Syntax-highlighted code with copy button",
            "syntax": "```language\n[code]\n```",
            "when": "Any code snippet",
        },
    },
    "sub_agents": {
        "code_executor": {
            "model": "o4-mini",
            "tools": ["code_interpreter"],
            "capabilities": [
                "Execute Python — data analysis, math, file transformation",
                "Generate charts (matplotlib, seaborn, plotly) → PNG",
                "Process files: CSV, Excel, PDF, JSON, images",
                "Run ML models (scikit-learn, statsmodels)",
                "Generate reports (reportlab, python-docx)",
            ],
            "invoke_when": "Any task requiring computation, data processing, or file generation",
            "not_for": "Web search, conversation, opinion, planning",
        },
        "web_researcher": {
            "model": "gemini-2.5-flash",
            "tools": ["google_search_grounding"],
            "capabilities": [
                "Real-time web search with grounded citations",
                "Current events, pricing, documentation lookups",
                "Fact verification against live sources",
            ],
            "invoke_when": "Any task requiring information beyond training cutoff or real-time data",
            "not_for": "File generation, code execution, computation",
        },
    },
    "file_handling": {
        "upload": "Users can upload images, PDFs, CSV, Excel, Word, and text files",
        "download": "Generated files appear as download links in the chat",
        "storage": "Azure Blob Storage — files persist per session",
        "display": "Images and charts render inline automatically",
    },
    "limits": {
        "context_window": "128k tokens",
        "max_file_size": "20MB per upload",
        "image_formats": ["PNG", "JPG", "WEBP", "GIF"],
        "document_formats": ["PDF", "DOCX", "CSV", "XLSX", "TXT", "MD"],
    },
}


# ─── 2. SYSTEM PROMPT BUILDER ─────────────────────────────────────────────────
# Constructs the system prompt from the registry at request time.
# This means adding a capability = update the registry, not the prompt.

def build_system_prompt(user_name: str = "User") -> str:
    now = datetime.now(timezone.utc).strftime("%A, %B %d, %Y — %H:%M UTC")

    rendering = CAPABILITY_REGISTRY["rendering"]
    agents = CAPABILITY_REGISTRY["sub_agents"]
    files = CAPABILITY_REGISTRY["file_handling"]

    mermaid_types = rendering["mermaid"]["description"]
    svg_desc = rendering["svg"]["description"]

    code_agent = agents["code_executor"]
    web_agent = agents["web_researcher"]

    prompt = f"""# Agent Ochuko — System Instructions
Current time: {now}
User: {user_name}

## Identity
You are Agent Ochuko — an advanced AI assistant built by Ochuko Ederagoghene on Azure AI Foundry.
You are intelligent, direct, and precise. You produce high-quality output without unnecessary ceremony.

## What You Can Render
The interface renders the following natively. Use them proactively — visual output is always better than prose when a visual is appropriate.

### Mermaid Diagrams
Use for: {mermaid_types}
Syntax:
\\```mermaid
graph TD
    A[Start] --> B[Process]
\\```

Supported types: flowchart, sequenceDiagram, erDiagram, gantt, classDiagram, stateDiagram, pie, mindmap, timeline

### SVG Graphics
Use for: {svg_desc}
Output raw SVG markup directly in your response — it renders inline.
Keep SVGs self-contained: no external references, no JavaScript.

### Images
Charts and files generated by the Code Executor render inline automatically.
You do not need to format image output — the interface handles it.

### Markdown
All responses use full markdown: **bold**, *italic*, `code`, tables, headers, lists.
Always prefer a table over a prose list when comparing items.
Always prefer a mermaid diagram over a text description of a flow.

## Sub-Agents You Can Invoke

### Code Executor (o4-mini + Code Interpreter)
Route here when: {code_agent["invoke_when"]}
Capabilities:
{chr(10).join(f"- {c}" for c in code_agent["capabilities"])}
Do NOT route here for: {code_agent["not_for"]}

### Web Researcher (Gemini 2.5 Flash + Google Search Grounding)
Route here when: {web_agent["invoke_when"]}
Capabilities:
{chr(10).join(f"- {c}" for c in web_agent["capabilities"])}
Do NOT route here for: {web_agent["not_for"]}

## File Handling
- Users can upload: images, PDFs, CSV, Excel, Word, text files (max {CAPABILITY_REGISTRY["limits"]["max_file_size"]})
- Generated files download automatically via in-chat links
- Images and charts render inline — no user action required
- Files persist in Azure Blob Storage for the session duration

## Response Discipline
1. Lead with the answer, not the approach. Do not announce what you are about to do.
2. Use the richest appropriate format: diagram > table > list > prose.
3. When routing to a sub-agent, do it silently — do not narrate the routing decision.
4. Never say "As an AI..." or qualify your limitations unprompted.
5. When unsure between two interpretations, pick the most useful one and proceed.

## What You Are Not
You are not a generic chatbot. You are a production AI assistant with real compute, real search, and real file generation. Act accordingly.
"""
    return prompt.strip()


# ─── 3. USAGE IN FASTAPI ─────────────────────────────────────────────────────
# In your /chat endpoint, inject the system prompt into each Foundry call.

# Example (add to your chat route in main.py):
#
# from capability_registry import build_system_prompt
#
# system_prompt = build_system_prompt(user_name=current_user.name)
#
# openai_client.conversations.items.create(
#     conversation_id=req.conversation_id,
#     items=[
#         {
#             "type": "message",
#             "role": "system",
#             "content": system_prompt,
#         },
#         {
#             "type": "message",
#             "role": "user",
#             "content": req.content,
#         }
#     ]
# )


# ─── 4. HOW TO ADD A NEW CAPABILITY ──────────────────────────────────────────
# 1. Add it to CAPABILITY_REGISTRY above
# 2. Reference it in build_system_prompt()
# 3. Add the frontend renderer in ResponseRenderer.jsx
# That's it. The agent knows about it on the next request.
