# app/core/capability_registry.py
"""
Capability self-awareness layer for Agent Ochuko.

This module is the single source of truth for what the agent can render
and which sub-agents it can route to.

build_capability_section() generates the rendering + sub-agent section
of the system prompt at request time. It is injected into full_system
in chat.py AFTER _OCHUKO_RULE (which already covers identity + tone).

To add a capability:
  1. Add it to CAPABILITY_REGISTRY below.
  2. Reference it in build_capability_section() if needed.
  3. Add the frontend renderer in Dashboard.tsx.
  That's it. The agent knows about it on the next request.
"""

from datetime import datetime, timezone

# ─── CAPABILITY REGISTRY ──────────────────────────────────────────────────────
# Single source of truth. Add/remove capabilities here.

CAPABILITY_REGISTRY = {
    "rendering": {
        "mermaid": {
            "description": "Flowcharts, sequence diagrams, ER diagrams, Gantt charts, class diagrams, state diagrams, pie charts, mindmaps, timelines",
            "syntax": "```mermaid\n[diagram code]\n```",
            "when": "Architecture, workflows, data relationships, process flows, timelines — always prefer this over describing a flow in prose",
        },
        "svg": {
            "description": "Scalable vector graphics — icons, illustrations, custom visuals",
            "syntax": "Output raw <svg>...</svg> markup inline in your response",
            "when": "Custom icons, geometric diagrams, logos, decorative visuals. Keep SVGs self-contained: no external references, no JavaScript.",
        },
        "images": {
            "description": "PNG/JPG/SVG files generated by the Code Executor",
            "syntax": "Files from Code Executor display automatically — no extra formatting needed",
            "when": "Charts, plots, processed images, data visualisations",
            "generation_trigger": "When user asks for a chart, plot, visualization, or image output from code. Direct the Code Executor to generate and save the file, and reference it in the assistant message. Do NOT use image_generator sub-agent.",
        },
        "markdown": {
            "description": "Full markdown including tables, bold, italic, code, links, headers, lists",
            "syntax": "Standard markdown",
            "when": "All prose — always use markdown. Always prefer a table over a prose list when comparing items.",
        },
        "code_blocks": {
            "description": "Syntax-highlighted code blocks with a copy button",
            "syntax": "```language\n[code]\n```",
            "when": "Any code snippet",
        },
        "latex": {
            "description": "Mathematical expressions rendered via KaTeX",
            "syntax": "Inline: $expression$  |  Block: $$expression$$",
            "when": "Any mathematical notation, formulas, equations",
        },
    },
    "sub_agents": {
        "code_executor": {
            "model": "o4-mini",
            "tools": ["code_interpreter"],
            "capabilities": [
                "Execute Python — data analysis, math, file transformation",
                "Generate charts (matplotlib, seaborn, plotly) → PNG",
                "Process files: CSV, Excel, PDF, JSON, images",
                "Run ML models (scikit-learn, statsmodels)",
                "Generate reports (reportlab, python-docx)",
                "Create PDF documents (reportlab, fpdf2, weasyprint)",
                "Create DOCX files (python-docx)",
                "Create Excel spreadsheets (openpyxl, xlsxwriter)",
            ],
            "invoke_when": (
                "Any task requiring computation, data processing, file generation, or executable code. "
                "CRITICAL: When a user asks to CREATE, GENERATE, MAKE, BUILD, or EXPORT any document — "
                "CV, resume, report, invoice, proposal, letter, spreadsheet, PDF, DOCX — "
                "you MUST use the Code Executor to produce the actual file. "
                "NEVER return the content as text. ALWAYS generate the downloadable file."
            ),
            "not_for": "Web search, conversation, opinion, planning (without file output)",
            "file_generation_libs": {
                "pdf": ["reportlab", "fpdf2"],
                "docx": ["python-docx"],
                "excel": ["openpyxl", "xlsxwriter"],
                "csv": ["csv (stdlib)", "pandas"],
            },
        },
        "web_researcher": {
            "model": "gemini-2.5-flash",
            "tools": ["google_search_grounding"],
            "capabilities": [
                "Real-time web search with grounded citations",
                "Current events, pricing, live documentation",
                "Fact verification against live sources",
            ],
            "invoke_when": "Any task requiring information beyond training cutoff or real-time data",
            "not_for": "File generation, code execution, computation",
        },
        "image_generator": {
            "model": "FLUX (Azure AI)",
            "tools": ["generate_image"],
            "capabilities": [
                "Generate high-quality images from text descriptions",
                "Photorealistic scenes, illustrations, concept art",
                "Logos, banners, diagrams rendered as images",
                "Product mockups, UI wireframes as images",
            ],
            "invoke_when": "User asks to create, draw, generate, illustrate, or visualise anything as an image",
            "not_for": "Structured diagrams (use Mermaid), data charts (use Code Executor), web search",
        },
    },
    "file_handling": {
        "upload": "Users can upload images, PDFs, CSV, Excel, Word, and text files (max 20 MB)",
        "download": "Generated files appear as download cards in the chat bubble automatically",
        "storage": "Cloudflare R2 — files persist across sessions",
        "display": "Images and charts render inline — no user action required",
    },
}


# ─── CAPABILITY SECTION BUILDER ───────────────────────────────────────────────
# Generates only the rendering + sub-agent section of the system prompt.
# Identity + tone are already in _OCHUKO_RULE in chat.py — no duplication.

def build_capability_section() -> str:
    r = CAPABILITY_REGISTRY["rendering"]
    sa = CAPABILITY_REGISTRY["sub_agents"]
    fh = CAPABILITY_REGISTRY["file_handling"]

    code_agent = sa["code_executor"]
    web_agent = sa["web_researcher"]
    img_agent = sa["image_generator"]

    section = f"""
## Visual Output — Use These Proactively

The interface renders the following natively. Visual output is always better than prose when a visual is appropriate.

### Mermaid Diagrams
When to use: {r['mermaid']['when']}
Supported types: flowchart, sequenceDiagram, erDiagram, gantt, classDiagram, stateDiagram, pie, mindmap, timeline
Syntax:
```mermaid
graph TD
    A[Start] --> B[Process]
```

### SVG Graphics
When to use: {r['svg']['when']}
{r['svg']['syntax']}

### LaTeX / Math
When to use: {r['latex']['when']}
Syntax: {r['latex']['syntax']}

### Visual Hierarchy Rule
diagram > table > list > prose
Always pick the richest appropriate format. Never describe a flow in prose if a diagram fits.

---

## Sub-Agents Available

### Image Generator (FLUX via Azure AI)
Route here when: {img_agent['invoke_when']}
Capabilities:
{chr(10).join(f"- {c}" for c in img_agent['capabilities'])}
Do NOT route here for: {img_agent['not_for']}

### Code Executor (o4-mini + Code Interpreter)
Route here when: Any task requiring computation, data processing, code execution, or file generation.

**ABSOLUTE RULE — File Generation:**
When a user asks to create, generate, make, build, or export ANY document — CV, resume, report, invoice, proposal, letter, spreadsheet, PDF, DOCX, CSV — you MUST use the Code Executor to produce the actual downloadable file. NEVER return the content as text. ALWAYS generate the file.

Available libraries:
- PDF: `reportlab`, `fpdf2`
- DOCX: `python-docx`
- Excel: `openpyxl`, `xlsxwriter`
- Data: `pandas`, `csv`

Capabilities:
{chr(10).join(f"- {c}" for c in code_agent['capabilities'])}
Do NOT route here for: {code_agent['not_for']}

### Web Researcher (Gemini 2.5 Flash + Google Search)
Route here when: {web_agent['invoke_when']}
Capabilities:
{chr(10).join(f"- {c}" for c in web_agent['capabilities'])}
Do NOT route here for: {web_agent['not_for']}

---

## File Handling
- Users can upload: images, PDFs, CSV, Excel, Word, text (max 20 MB)
- Generated files appear as download cards automatically — no formatting needed
- Charts and images render inline — no extra markup required
"""
    return section.strip()
